version: 2

name: CircleCI

on: [ push, pull_request ]

jobs:
  lint:
    docker:
      - image: cimg/node:14.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn add eslint
      - run: yarn run lint
  build:
    docker:
      - image: cimg/node:14.0
    steps:
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Lint
          command: yarn eslint src
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
