version: 2

name: CircleCI

on: [ push, pull_request ]

jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Lint
          command: yarn eslint src
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
